#!/bin/bash
#
# Make the PATH empty and check if /bin/ls still works

command="/bin/ls"
tmp_file="checker_tmp_file_$RANDOM"

# Clean up
stop_shell
rm -f $tmp_file

# Create a pseudo random file
touch $tmp_file
# Empty PATH
OLDPATH="$PATH"
PATH=""
# Send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# Put PATH back
PATH="$OLDPATH"

# Wait a little bit
$SLEEP $SLEEPSECONDS

cat $ERROROUTPUTFILE

# Check the result
nmatch=`$CAT $OUTPUTFILE | $GREP -c "$tmp_file"`
if [ $nmatch -eq 1 ]; then
    print_ok
else
    print_ko
fi

# Clean up
stop_shell
$RM -f $tmp_file
