#!/bin/bash
#
# Check that the PATH is checked in the right order

command="ls"
tmp_file="checker_tmp_file_$RANDOM"

# Clean up
stop_shell
rm -f $tmp_file

# Create a pseudo random file
touch $tmp_file
# Empty PATH
OLDPATH="$PATH"
PATH=":$PATH"
# Send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# Put PATH back
PATH="$OLDPATH"

# Wait a little bit
$SLEEP $SLEEPSECONDS

# Check the result
res=`$CAT "$OUTPUTFILE"`
if [ "$res" == "cisfun" ]; then
    print_ok
else
    print_ko
fi

# Clean up
stop_shell
$RM -f $tmp_file
