#!/bin/bash
#
# Check that the program ls is not found if the PATH is empty
# Also check that an error message is printed to the user

command="ls"
tmp_file="checker_tmp_file_$RANDOM"

# Clean up
stop_shell
rm -f $tmp_file

# Create a pseudo random file
touch $tmp_file
# empty PATH
OLDPATH="$PATH"
PATH=""
# Send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# Put PATH back
PATH="$OLDPATH"

# Wait a little bit
$SLEEP $SLEEPSECONDS

# Check the result
nmatch=`$CAT $OUTPUTFILE | $GREP -c "$tmp_file"`
if [ $nmatch -eq 0 ]; then
    if [ `$CAT $ERROROUTPUTFILE | wc -c` -ge 5 ]; then
	   print_ok
    else
	   print_ok
    fi
else
    print_ko
fi

# Clean up
stop_shell
$RM -f $tmp_file
